global using NUnit.Framework;
global using AspNetServer.Data;
global using Microsoft.EntityFrameworkCore;
global using AspNetServer.Controllers;
global using AspNetServer.Services.NewsService;
global using AspNetServer.Utilities;
global using Microsoft.AspNetCore.Mvc;
global using AspNetServer.Tests.Mocks;
global using AspNetServer.Models;